### ISSUE TITLE
How can I test the model and create.h5 file?

### ISSUE THREAD

**Issue by terawise** [rongliangzi/Dense-Scale-Network-for-Crowd-Counting#3]
Hi,

I am a newbie who is studying crowd counting.
According to the survey paper, your work performs excellent.
I have traced your code and trained the model, it seems need a h5 to test your model? How can I use a photo from the internet to test your model? And how can I create a h5 file of it?
Thanks

**Comment by rongliangzi** [comment]
I have uploaded the code for data preparation and model testing on one image or a dataset.

**Comment by terawise** [comment]
thanks :)
